### ISSUE TITLE
Ensure all links and resources are requested via HTTPS

### ISSUE THREAD

**Issue by AyupMike** [RoyalBoroughKingston/ck-frontend#118]
The front-end will be entirely delivered via HTTPS - need to ensure we don't get any "insecure" page warning when requesting resources

**Comment by seanjessen** [comment]
@AyupMike - I've done a find on the entire codebase and only links in SVGs aren't HTTPS

**Comment by AyupMike** [comment]
Ok cook - yeh don't update the SVG schemas as SVGs prob wont be valid/work
