### ISSUE TITLE
Search - Add useful information box in sidebar for persona and category

### ISSUE THREAD

**Issue by seanjessen** [RoyalBoroughKingston/ck-frontend#93]

**Comment by seanjessen** [comment]
@AyupMike @matthew-inamdar Is data currently coming from the API cause I can't see it for category or persona

**Comment by matthew-inamdar** [comment]
Hey @seanjessen - do we currently show the categories and personas a service falls within on the frontend?

It's a complex relationship as a service and collection aren't directly linked, but rather both share the same taxonomies.

**Comment by seanjessen** [comment]
@matthew-inamdar No this is not shown on a service.

This issue was more regarding the box on the side underneath filter on this invision link:
https://projects.invisionapp.com/share/C6N8I9AAK2Y#/screens/311726266

There is a comment on it saying content will pull from the API but I am unsure as to what to display here as there aren't really any fields to display

**Comment by matthew-inamdar** [comment]
@seanjessen - This seems to be the info for the organisation?

**Comment by matthew-inamdar** [comment]
@seanjessen - not sure on this one? @AyupMike ?

**Comment by AyupMike** [comment]
API needs to be updated to enable this. Issue closed and work needs to be moved into the next phase
