### ISSUE TITLE
Location Search Not working

### ISSUE THREAD

**Issue by seanjessen** [RoyalBoroughKingston/ck-frontend#95]
Any UK postcode returns the same result

**Comment by matthew-inamdar** [comment]
@seanjessen - this is due to all locations having the same lat/long - I need to update these which I'll try get done tonight. Will update once doen

**Comment by matthew-inamdar** [comment]
This fix has been deployed

**Comment by seanjessen** [comment]
This still seems to return all results if I enter a postcode outside of kingston

**Comment by matthew-inamdar** [comment]
@seanjessen - it doesn't filter out any results, it only orders them by distance.

**Comment by seanjessen** [comment]
@matthew-inamdar No problem just wanted to double check, will closes this then
